/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D GINEBRA.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0.23, -0.03, -0.01]} rotation={[0, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq2_ARD-geom"].geometry}
          material={materials.tq2_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq2_ARD-geom_1"].geometry}
          material={materials.tq2_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq2_ARD-geom_2"].geometry}
          material={materials.tq2_ARD_edge}
        />
      </group>
      <group position={[-0.22, -0.01, 0.18]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom"].geometry}
          material={materials.TQ_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom_1"].geometry}
          material={materials.TQ_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom_2"].geometry}
          material={materials.TQ_ARD_edge}
        />
      </group>
      <group position={[0.22, 0, -0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom001"].geometry}
          material={materials["TQ_ARD_front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom001_1"].geometry}
          material={materials["TQ_ARD_back.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom001_2"].geometry}
          material={materials["TQ_ARD_edge.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D GINEBRA.gltf");
